before_script:
  - time git submodule sync --recursive
  - time git submodule update --init --recursive
build:
  image: alessiomorale/gcc-arm-none-eabi-ci:release-1.0.0-gcc9-2019q4
  script:
    - cd firmware
    - time make cpputest -j4
    - time make test all -j4
    
