before_script:
  - apt-get update -qq && apt-get install -y software-properties-common --no-install-recommends
  - add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - apt-get update -qq && apt-get install -y -qq gcc-arm-none-eabi make git
  - git submodule sync --recursive
  - git submodule update --init --recursive
build:
  image: ubuntu:18.04
  script:
    - cd UNAVng/UNAVng_fw
    - make -j4
    
