before_script:
  - apt update && apt install autoconf libtool g++ -y
  - git submodule sync --recursive
  - git submodule update --init --recursive
build:
  image: alessiomorale/gcc-arm-none-eabi-ci:latest
  script:
    - cd firmware
    - make -j4
    
