before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
build:
  image: alessiomorale/gcc-arm-none-eabi-ci:latest
  script:
    - cd UNAVng/UNAVng_fw
    - make -j4
    
