before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
build:
  image: alessiomorale/gcc-arm-none-eabi-ci:release-1.1.0
  script:
    - cd firmware
    - make cpputest -j4
    - make test all -j4
    
