name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alessiomorale/gcc-arm-none-eabi-ci:release-1.0.1-gcc9-2019q4
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: cd firmware && make cpputest -j4 && make test all -j4
